### ISSUE TITLE
loading non existent list, better error message

### ISSUE THREAD

**Issue by globalworming** [globalworming/todo-list-fullstack#13]

**Comment by tudiapason** [comment]
Hello

My understanding of the code workflow is that:
1. In the MockDatastoreClient class from todo-service, the BDD response is simulated, so error messages are generated when the list does not exist, for example.
2. In ToDoService class from todo-service, the different action methods catch the errors and convert them to RuntimeException before sending them to BFF layer.
3. In MyErrorHandler class from BFF, we handle and format errors before sending them to the front end.
In the handle method, the system use .toSting() to format the JSON error before sending it that is why we see all the error attributes as type and message displayed on the Web page.

So I propose reviewing the MyErrorHandler class to extract expected information before sending the error label to the front end. See my change in the following fork:
https://github.com/tudiapason/todo-list-fullstack/tree/main
